/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.MyScene {
    export class HomeUI extends Scene {
		public tipBg:Laya.Sprite;
		public logo:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("MyScene/Home");
        }
    }
    REG("ui.MyScene.HomeUI",HomeUI);
    export class LoadUI extends Scene {
		public loading:Laya.Sprite;
		public logo:Laya.Sprite;
		public hethTip:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("MyScene/Load");
        }
    }
    REG("ui.MyScene.LoadUI",LoadUI);
    export class MainUI extends Scene {
		public mainBg:Laya.Sprite;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("MyScene/Main");
        }
    }
    REG("ui.MyScene.MainUI",MainUI);
}